image: node:latest

cache:
  paths:
    - node_modules/

stages:
    - build
    - deploy

build:
    script:
        - npm i
        - npm run build
    stage: build

pages:
  stage: deploy
  artifacts:
    paths:
      - dist
